version: '3.8' 
# docker compose logs -f: to see the logs file 
# docker compose -f docker-compose-production.yaml up --scale app=2

services:
  app:
    image: hungmanhhoang/room-visualizer-app:2.0 
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload" 
    volumes:
      - ./room_wall_visualizer/app/Room_Wall_Visualizer:/app  
    restart: always

  nginx:
    build: nginx  
    ports:
      - "80:80"   
      - "443:443"  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always